### ISSUE TITLE
Can't seem to find package in Maven

### ISSUE THREAD

**Issue by johanhaleby** [unbroken-dome/siren-java#1]
Hi, 

I'm trying to use the library but it doesn't seem to be available in neither JCenter or Maven Central afaict. Searching in bintray I find [this](https://bintray.com/till-krullmann/tools/siren-core) package which says:

```xml
<dependency> 
	<groupId>org.unbroken-dome.siren</groupId> 
	<artifactId>siren-core</artifactId> 
	<version>0.2.0</version>
</dependency>
```

Note that this is not the same groupId that's specified in the readme. 

I've tried added the jcenter repository:

```xml
<repositories>
        <repository>
            <id>jcenter</id>
            <url>https://jcenter.bintray.com/</url>
        </repository>
 </repositories>
```

but it doesn't seem to help.

**Comment by tkrullmann** [comment]
You're right, I never really sent the request to Bintray to include it in JCenter. Did that now, it should be available soon!

**Comment by johanhaleby** [comment]
Thanks!
